<a href="https://colab.research.google.com/github/PineappleBingo/CSC448-AI/blob/main/CSC448_Seo_Jinho_AS04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Imports and pip installations (if needed)
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part 1: Load the dataset

In [13]:
# Load the dataset (load remotely, not locally)

iris = load_iris()

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
# columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])

df["target"] = iris.target

# Output the first 15 rows of the data
print(df.head(15))


    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4 

In [14]:
# Display a summary of the table information (number of datapoints, etc.)
print(df.info())
print("\nRow x Columns:", df.shape)
print("\nNumber of dataset:", df.shape[0])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB
None

Row x Columns: (150, 5)

Number of dataset: 150


## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

In [15]:
# The Iris Dataset is a multi-class classification flower dataset that 
# contains 150 records from three different types of species: 
# Iris setosa, Iris versicolor and Iris virginica. 

# Features:
IrisF = df.columns
print("Iris features:")
for i in range(0,4):
    print(IrisF[i])

# Label:
# Iris species
print("\nLabel: Iris Species")

# The mapping:
print("\nThe Mapping:")
Y = iris.target
IC = np.unique(Y)
IrisC = ('Setosa','Versicolor','Virginica')

for i in range(0,3):
    print (IC[i], IrisC[i])



Iris features:
sepal length (cm)
sepal width (cm)
petal length (cm)
petal width (cm)

Label: Iris Species

The Mapping:
0 Setosa
1 Versicolor
2 Virginica


# Part 2: Split the dataset into train and test

In [16]:
# Take the dataset and split it into our features (X) and label (y)

# features X
features = df[iris.feature_names]
# lable Y
label = df["target"]

X, Y = features, label 

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=10)


# Part 3: Logistic Regression

In [17]:
# i. Use sklearn to train a LogisticRegression model on the training set
log_reg_model  = LogisticRegression().fit(X_train, Y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
sample = np.array([[2,3,2,3]])

log_model_prob = log_reg_model.predict_proba(sample)

print("Probability for each possible classes: ")
for idx in range(0, 3):
    print("{:<10}{:<10}{}{}".format(str(sample[0]), str(IrisC[idx])," -> probability:", log_model_prob[0][idx]))
print("------------------------------------------------------")

# iii. Report on the score for Logistic regression model, what does the score measure?
log_model_score = log_reg_model.score(X_test, Y_test)
print("The score for the Logistic Regression Model: ", log_model_score)
print("------------------------------------------------------")

# It measures the performance or accuracy of the Logistic Regression model.
# The score 100% means that this model correctly classifying each classes of dataset


# iv. Extract the coefficents and Intercepts for the boundary line(s)
coefficients = log_reg_model.coef_
print("Coefficients for each possible classes:")
for idx in range(0, 3):
    print("{:<10}{:<10}{}{}".format(str(sample[0]), str(IrisC[idx]), " -> Coefficients:", coefficients[idx]))

print("------------------------------------------------------")
# intercept 
intercept  = log_reg_model.intercept_
print("Intercepts for each possible classe:")
for idx in range(0, 3):
    print("{:<10}{:<10}{}{}".format(str(sample[0]), str(IrisC[idx]), " -> Intercept: ", intercept[idx]))
print("------------------------------------------------------")



Probability for each possible classes: 
[2 3 2 3] Setosa     -> probability:0.9847075998816394
[2 3 2 3] Versicolor -> probability:0.013102699516003286
[2 3 2 3] Virginica  -> probability:0.0021897006023574236
------------------------------------------------------
The score for the Logistic Regression Model:  1.0
------------------------------------------------------
Coefficients for each possible classes:
[2 3 2 3] Setosa     -> Coefficients:[-0.42179578  0.93564604 -2.43711991 -1.05535041]
[2 3 2 3] Versicolor -> Coefficients:[ 0.53578775 -0.25471659 -0.2074305  -0.8459005 ]
[2 3 2 3] Virginica  -> Coefficients:[-0.11399197 -0.68092946  2.64455041  1.90125091]
------------------------------------------------------
Intercepts for each possible classe:
[2 3 2 3] Setosa     -> Intercept: 9.552979926317207
[2 3 2 3] Versicolor -> Intercept: 1.8016457728697521
[2 3 2 3] Virginica  -> Intercept: -11.354625699187194
------------------------------------------------------


D:\Program Files\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Program Files\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


# Part 4: Support Vector Machine

In [18]:
# i. Use sklearn to train a Support Vector Classifier on the training set

svm_model = SVC(probability=True)
svm_model.fit(X_train, Y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class

# predict_proba will give the possibility of each class given the sample point
# The model predicts that each of the probabilities belongs to each class [0,1,2]
# classes = np.array([[2,3,2,3]])
svm_pred = svm_model.predict(np.array(sample))

print("Probability for each possible class: ", svm_pred)
# [0]: Setosa Probability

print("------------------------------------------------------")

# iii. Report on the score for the SVM, what does the score measure?
svm_model_score = svm_model.score(X_test, Y_test)
print("Accuracy of the SVC Clasification is: ", svm_model_score)

# it measures that the classification is %100 correct
print("------------------------------------------------------")


Probability for each possible class:  [0]
------------------------------------------------------
Accuracy of the SVC Clasification is:  1.0
------------------------------------------------------


D:\Program Files\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


# Part 5: Neural Network

In [19]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set

mlp_model = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(15,),random_state=1).fit(features, label)

# ii. For a sample datapoint, predict the probabilities for each possible class
# sample = np.array([[2,3,2,3]])
mlp_model_pred = mlp_model.predict_proba(sample)

print("Probability for each possible classes: ")
for idx in range(0, 3):
    print("{:<10}{:<10}{}{}".format(str(sample[0]), str(IrisC[idx])," -> probability: ", mlp_model_pred[0][idx]))
print("------------------------------------------------------")

# iii. Report on the score for the Neural Network, what does the score measure?
mlp_model_score = mlp_model.score(X_test, Y_test)
print("Accuracy of the Neural Network Clasification: ", mlp_model_score)
print("------------------------------------------------------")

# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)
mlp_model = MLPClassifier(solver='sgd', alpha=1e-5,hidden_layer_sizes=(15,),random_state=1).fit(features, label)

# sample = np.array([[2,3,2,3]])
mlp_model_pred = mlp_model.predict_proba(sample)

print("Probability for each possible classes: ")
for idx in range(0, 3):
    print("{:<10}{:<10}{}{}".format(str(sample[0]), str(IrisC[idx])," -> probability: ", mlp_model_pred[0][idx]))
print("------------------------------------------------------")

mlp_model_score = mlp_model.score(X_test, Y_test)
print("Accuracy of the Neural Network Clasification: ", mlp_model_score)
print("------------------------------------------------------")


Probability for each possible classes: 
[2 3 2 3] Setosa     -> probability: 3.694674403478e-239
[2 3 2 3] Versicolor -> probability: 1.0
[2 3 2 3] Virginica  -> probability: 4.1277849627003388e-22
------------------------------------------------------
Accuracy of the Neural Network Clasification:  1.0
------------------------------------------------------
Probability for each possible classes: 
[2 3 2 3] Setosa     -> probability: 0.6182893047418228
[2 3 2 3] Versicolor -> probability: 0.1344155881768067
[2 3 2 3] Virginica  -> probability: 0.2472951070813706
------------------------------------------------------
Accuracy of the Neural Network Clasification:  0.5333333333333333
------------------------------------------------------


D:\Program Files\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
D:\Program Files\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
D:\Program Files\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


# Part 6: K-Nearest Neighbors

In [20]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier

knn_model = KNeighborsClassifier(n_neighbors=9)
knn_model.fit(X_train, Y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
# sample = np.array([[2,3,2,3]])
knn_model_pred = knn_model.predict_proba(sample)
print("Probability for each possible classes: ")
for idx in range(0, 3):
    print("{:<10}{:<10}{}{}".format(str(sample[0]), str(IrisC[idx])," -> probability: ", knn_model_pred[0][idx]))
print("------------------------------------------------------")


# iii. Report on the score for kNN, what does the score measure?
knn_model_score = knn_model.score(X_test, Y_test)
print("Accuracy of the K-Nearest Neighbors Clasification: ", knn_model_score)
print("------------------------------------------------------")

Probability for each possible classes: 
[2 3 2 3] Setosa     -> probability: 0.7777777777777778
[2 3 2 3] Versicolor -> probability: 0.2222222222222222
[2 3 2 3] Virginica  -> probability: 0.0
------------------------------------------------------
Accuracy of the K-Nearest Neighbors Clasification:  0.9333333333333333
------------------------------------------------------


D:\Program Files\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?


In [21]:
# According to the result of each models' accuracy scores, the performance score was very similar for all the predition models. The most accurated models are 
# logistic regression model and SVM. Most cases each model classified the sample dataset predicted as [0]:Setosa.  
